import json
import os
import signal
from pathlib import Path
from unittest import mock

import pytest

from wsqlite_mcp import server

# --- get_catalog ---


def test_get_catalog_returns_shared_singleton():
    server.get_catalog.cache_clear()
    c1 = server.get_catalog()
    c2 = server.get_catalog()
    assert c1 is c2
    server.get_catalog.cache_clear()


# --- blueprints tool ---


def test_blueprints_contains_all_15_features():
    text = server.get_wsqlite_architect_blueprints()
    sections = [
        "=== 1. MODEL & CRUD",
        "=== 2. ASYNC OPERATIONS",
        "=== 3. BATCH OPERATIONS",
        "=== 4. TRANSACTIONS",
        "=== 5. RELATIONSHIPS",
        "=== 6. QUERY BUILDER",
        "=== 7. FTS5 SEARCH",
        "=== 8. MIGRATIONS",
        "=== 9. CONNECTION POOL",
        "=== 10. SOFT DELETE",
        "=== 11. PAGINATION",
        "=== 12. RETRY ON LOCK",
        "=== 13. RAW SQL WITH POOL",
        "=== 14. MODEL CONSTRAINTS",
        "=== 15. TABLESYNC",
    ]
    for s in sections:
        assert s in text
    assert "WSQLITE EXPERT BLUEPRINTS" in text
    assert "read/write/update" in text.lower()


# --- search tool ---


def test_search_wsqlite_pattern_returns_results():
    patterns = [
        {
            "origin": "Official",
            "name": "model_crud_basic",
            "feature": "WSQLite CRUD",
            "module": "wsqlite",
            "description": "auto table creation",
        },
        {
            "origin": "Community",
            "name": "fts5_search",
            "feature": "FTS5",
            "module": "wsqlite",
            "description": "full-text search",
        },
    ]
    catalog_mock = mock.MagicMock()
    catalog_mock.search.return_value = patterns
    with mock.patch.object(server, "get_catalog", return_value=catalog_mock):
        text = server.search_wsqlite_pattern("crud")
    assert "model_crud_basic" in text
    assert "WSQLite CRUD" in text
    assert "wsqlite" in text
    assert "auto table creation" in text
    assert "Official" in text
    assert "Community" in text


def test_search_wsqlite_pattern_no_results():
    catalog_mock = mock.MagicMock()
    catalog_mock.search.return_value = []
    with mock.patch.object(server, "get_catalog", return_value=catalog_mock):
        text = server.search_wsqlite_pattern("zzz_nope")
    assert "No pattern matching 'zzz_nope' was found" in text
    assert "native WSQLite pattern" in text


# --- deploy scaffolding tool ---


def test_deploy_wsqlite_scaffolding_relative_path_rejected():
    text = server.deploy_wsqlite_scaffolding("relative/path")
    assert text.startswith("Error:")
    assert "absolute path" in text


def test_deploy_wsqlite_scaffolding_creates_project(tmp_path):
    target = str(tmp_path / "deployed")
    result = server.deploy_wsqlite_scaffolding(target, project_name="MyApp", scaffold_type="api_service")

    assert result.startswith("Success:")
    assert "MyApp" in result
    assert (tmp_path / "deployed" / "main.py").exists()
    assert (tmp_path / "deployed" / "config" / "settings.py").exists()
    assert (tmp_path / "deployed" / "models" / "user.py").exists()
    assert (tmp_path / "deployed" / "repositories" / "user_repo.py").exists()
    assert (tmp_path / "deployed" / "migrations" / "manager.py").exists()
    assert (tmp_path / "deployed" / "wsqlite.config.json").exists()


def test_deploy_wsqlite_scaffolding_exception_returns_error(tmp_path):
    target = str(tmp_path / "blocked")
    with mock.patch.object(server.TemplateGenerator, "get_folders", side_effect=OSError("disk full")):
        text = server.deploy_wsqlite_scaffolding(target)
    assert text == "Error: disk full"


def test_deploy_wsqlite_scaffolding_relative_path_after_abs():
    text = server.deploy_wsqlite_scaffolding("x", scaffold_type="bogus")
    assert text.startswith("Error:")
    assert "absolute path" in text


# --- manual tool ---


def test_manual_contains_guides():
    text = server.get_wsqlite_architect_manual()
    assert "WSQLITE ARCHITECT MANUAL" in text
    assert "PROJECT STRUCTURE RULES" in text
    assert "CORE RULES" in text
    assert "DATA STRUCTURE SELECTION GUIDE" in text
    assert "MODULE MAP" in text
    assert "REFACTORING A MONOLITH TO WSQLITE" in text
    assert "mermaid" in text
    assert "Generated by WSQLite MCP by wisrovi" in text


# --- CLI run modes ---


def test_run_stdio_uses_stdio_transport():
    with mock.patch.object(server.mcp, "run") as mock_run:
        server.run_stdio()
    mock_run.assert_called_once_with(transport="stdio")


def test_run_sse_uses_sse_transport():
    with mock.patch.object(server.mcp, "run") as mock_run:
        server.run_sse()
    mock_run.assert_called_once_with(transport="sse")


# --- background management ---


def test_start_background_when_already_running(tmp_path, monkeypatch):
    monkeypatch.setattr(server, "PID_FILE", str(tmp_path / "pid"))
    (tmp_path / "pid").write_text("9999")
    with mock.patch("subprocess.Popen") as mock_popen:
        server.start_background()
    mock_popen.assert_not_called()


def test_start_background_launches_process(tmp_path, monkeypatch):
    monkeypatch.setattr(server, "PID_FILE", str(tmp_path / "pid"))
    with mock.patch("subprocess.Popen") as mock_popen:
        proc_mock = mock.MagicMock()
        proc_mock.__enter__ = mock.Mock(return_value=proc_mock)
        proc_mock.__exit__ = mock.Mock(return_value=False)
        proc_mock.pid = 4242
        mock_popen.return_value = proc_mock
        server.start_background()
    mock_popen.assert_called_once()
    assert (tmp_path / "pid").read_text() == "4242"


def test_stop_background_when_not_running(tmp_path, monkeypatch):
    monkeypatch.setattr(server, "PID_FILE", str(tmp_path / "nope"))
    with mock.patch("os.kill") as mock_kill:
        server.stop_background()
    mock_kill.assert_not_called()


def test_stop_background_kills_process(tmp_path, monkeypatch):
    pid_file = tmp_path / "pid"
    pid_file.write_text("7777")
    monkeypatch.setattr(server, "PID_FILE", str(pid_file))
    with mock.patch("os.kill") as mock_kill:
        server.stop_background()
    mock_kill.assert_called_once_with(7777, signal.SIGTERM)
    assert not pid_file.exists()


def test_stop_background_process_not_found(tmp_path, monkeypatch):
    pid_file = tmp_path / "pid"
    pid_file.write_text("7777")
    monkeypatch.setattr(server, "PID_FILE", str(pid_file))
    with mock.patch("os.kill", side_effect=ProcessLookupError):
        server.stop_background()
    assert not pid_file.exists()


# --- print_config ---


def _parse_first_json(text: str) -> dict:
    decoder = json.JSONDecoder()
    obj, _ = decoder.raw_decode(text, idx=text.index("{"))
    return obj


def test_print_config_to_stdout(capsys):
    server.print_config(write_file=False)
    captured = capsys.readouterr()
    data = _parse_first_json(captured.out)
    assert "wsqlite-mcp" in data["mcpServers"]
    assert data["mcpServers"]["wsqlite-mcp"]["args"] == ["-m", "wsqlite_mcp.server", "run"]
    assert "QUICK INSTALL COMMANDS" in captured.out
    assert "gemini mcp add wsqlite-mcp" in captured.out


def test_print_config_saves_file(tmp_path, monkeypatch, capsys):
    monkeypatch.chdir(tmp_path)
    server.print_config(write_file=True)
    config_path = tmp_path / ".agents" / "wsqlite-mcp.json"
    assert config_path.exists()
    data = json.loads(config_path.read_text())
    assert "wsqlite-mcp" in data["mcpServers"]
    captured = capsys.readouterr()
    assert "Configuration saved to" in captured.out


# --- main CLI entrypoint ---


def test_main_config_saves_file(tmp_path, monkeypatch, capsys):
    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(server.sys, "argv", ["wsqlite-mcp", "config"])
    server.main()
    assert (tmp_path / ".agents" / "wsqlite-mcp.json").exists()


def test_main_config_print_flag(tmp_path, monkeypatch, capsys):
    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(server.sys, "argv", ["wsqlite-mcp", "config", "--print"])
    server.main()
    captured = capsys.readouterr()
    _parse_first_json(captured.out)
    assert not (tmp_path / ".agents" / "wsqlite-mcp.json").exists()


def test_main_run_uses_stdio(monkeypatch):
    monkeypatch.setattr(server.sys, "argv", ["wsqlite-mcp", "run"])
    with mock.patch.object(server.mcp, "run") as mock_run:
        server.main()
    mock_run.assert_called_once_with(transport="stdio")


def test_main_run_sse(monkeypatch):
    monkeypatch.setattr(server.sys, "argv", ["wsqlite-mcp", "run-sse"])
    with mock.patch.object(server.mcp, "run") as mock_run:
        server.main()
    mock_run.assert_called_once_with(transport="sse")


def test_main_start(monkeypatch, tmp_path):
    monkeypatch.setattr(server, "PID_FILE", str(tmp_path / "pid"))
    monkeypatch.setattr(server.sys, "argv", ["wsqlite-mcp", "start"])
    with mock.patch("subprocess.Popen") as mock_popen:
        proc_mock = mock.MagicMock()
        proc_mock.__enter__ = mock.Mock(return_value=proc_mock)
        proc_mock.__exit__ = mock.Mock(return_value=False)
        proc_mock.pid = 555
        mock_popen.return_value = proc_mock
        server.main()
    assert (tmp_path / "pid").read_text() == "555"


def test_main_stop(monkeypatch, tmp_path):
    pid_file = tmp_path / "pid"
    pid_file.write_text("555")
    monkeypatch.setattr(server, "PID_FILE", str(pid_file))
    monkeypatch.setattr(server.sys, "argv", ["wsqlite-mcp", "stop"])
    with mock.patch("os.kill"):
        server.main()
    assert not pid_file.exists()


def test_main_help(monkeypatch, capsys):
    monkeypatch.setattr(server.sys, "argv", ["wsqlite-mcp", "help"])
    with mock.patch("argparse.ArgumentParser.print_help") as mock_help:
        server.main()
    mock_help.assert_called_once()


def test_main_default_command_runs_stdio(monkeypatch):
    monkeypatch.setattr(server.sys, "argv", ["wsqlite-mcp"])
    with mock.patch.object(server.mcp, "run") as mock_run:
        server.main()
    mock_run.assert_called_once_with(transport="stdio")
